name: obj_detect_board
description: The companion app for our paper.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^0.12.4
  socket_io_client: ^2.0.0-beta
  http: ^0.13.0
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  multicast_dns: ^0.2.2
  logging: ^0.11.3+2

dev_dependencies:
  pedantic: ^1.9.0
  
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true