name: obj_detect_board
description: The companion app for our paper.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.0-dev
  multicast_dns: ^0.3.1
  socket_io_client: ^2.0.0-beta
  http: ^0.13.3
  modal_bottom_sheet: ^2.0.0
  horizontal_picker: ^1.1.0
  logging: ^1.0.2
  network_info_plus: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_ume:  ^0.2.1
  flutter_ume_kit_ui: ^0.2.1  # null-safety version: ^0.2.1
  flutter_ume_kit_device: ^0.2.1  # null-safety version: ^0.2.1
  flutter_ume_kit_perf: ^0.2.1  # null-safety version: ^0.2.1
  flutter_ume_kit_show_code: ^0.2.1  # null-safety version: ^0.2.1
  flutter_ume_kit_console: ^0.2.1  # null-safety version: ^0.2.1
  
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true